[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
  let NERDTreeShowHidden = 1
'''

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
hook_add = '''
  let g:nerdtree_tabs_open_on_console_startup = 1
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = {
    \ 'colorscheme': 'Dracula',
    \ 'active': {
    \   'left': [ ['mode', 'paste'],
    \             ['fugitive', 'filename', 'gitgutter', 'ale']
    \           ],
    \   'right': [ ['lineinfo'], ['percent'],
    \              ['charcode', 'fileformat', 'fileencoding', 'filetype']
    \            ]
    \ },
    \ 'component': {
    \   'fugitive': '%{exists("*fugitive#head")?fugitive#head():""}'
    \ },
    \ 'component_visible_condition': {
    \   'fugitive': '(exists("*fugitive#head") && ""!=fugitive#head())'
    \ },
    \ 'component_function': {
    \   'gitgutter': 'LightlineGitGutter',
    \   'filename': 'LightlineFilename',
    \   'ale': 'ALEGetStatusLine'
    \ },
    \ 'separator': { 'left': ' ', 'right': ' ' },
    \ 'subseparator': { 'left': ' ', 'right': ' ' }
  \ }
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'ap/vim-buftabline'
hook_add = '''
  let g:buftabline_numbers = 0
  let g:buftabline_indicators = 1
  let g:buftabline_separators = 1
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
build = ':UpdateRemotePlugins'
on_i = 1
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#enable_smart_case = 1
  let g:deoplete#auto_complete_start_length = 1
'''

[[plugins]]
repo = 'kassio/neoterm'
hook_source = '''
  let g:neoterm_position = 'horizontal'
  let g:neoterm_automap_keys = ',tt'
'''
