[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-textobj-function'

[[plugins]]
repo = 'osyo-manga/vim-operator-search'
depends = ['vim-operator-user', 'vim-textobj-function', 'vim-textobj-user']

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'AndrewRadev/splitjoin.vim'
hook_source = '''
  let g:splitjoin_split_mapping = ''
  let g:splitjoin_join_mapping = ''
'''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'
hook_source = '''
  let g:EditorConfig_exclude_patterns = ['scp://.*']
'''

[[plugins]]
repo = 'jiangmiao/auto-pairs'
on_i = 1

[[plugins]]
repo = 'majutsushi/tagbar'
hook_source = '''
  let g:tagbar_left = 0
  let g:tagbar_autofocus = 1
  let g:tagbar_autoshowtag = 1

  let g:tagbar_type_ruby = {
    \ 'kinds' : [
      \ 'm:modules',
      \ 'c:classes',
      \ 'd:describes',
      \ 'C:contexts',
      \ 'f:methods',
      \ 'F:singleton methods'
    \ ]
  \ }

  let g:tagbar_type_go = {
    \ 'ctagstype' : 'go',
    \ 'kinds'     : [
      \ 'p:package',
      \ 'i:imports:1',
      \ 'c:constants',
      \ 'v:variables',
      \ 't:types',
      \ 'n:interfaces',
      \ 'w:fields',
      \ 'e:embedded',
      \ 'm:methods',
      \ 'r:constructor',
      \ 'f:functions'
    \ ],
    \ 'sro' : '.',
    \ 'kind2scope' : {
      \ 't' : 'ctype',
      \ 'n' : 'ntype'
    \ },
    \ 'scope2kind' : {
      \ 'ctype' : 't',
      \ 'ntype' : 'n'
    \ }
  \ }
'''

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]]
repo = 'soramugi/auto-ctags.vim'
hook_source = '''
  let g:auto_ctags = 1
  let g:auto_ctags_directory_list = ['.git']
'''

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = ['vim']
on_i = 1

[[plugins]]
repo = 'Shougo/neco-syntax'
on_i = 1

[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css']

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'php', 'css', 'scss']

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = ['slim']

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = ['jsx', 'javascript.jsx']

[[plugins]]
repo = 'trotzig/import-js'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'marijnh/tern_for_vim'
on_ft = ['javascript', 'javascript.jsx']
build = 'npm install -g tern'

[[plugin]]
repo = 'carlitux/deoplete-ternjs'
on_ft = ['javascript','javascript.jsx']
on_i = 1
hook_source = '''
  let g:tern#command = ["tern"]
  let g:tern#arguments = ["--persistent"]
'''

[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'
on_ft = ['javascript', 'javascript.jsx']
hook_source = '''
  let g:used_javascript_libs = 'jquery,react'
  let b:javascript_lib_use_jquery = 1
  let b:javascript_lib_use_react = 1
'''

[[plugins]]
repo = 'letientai299/vim-react-snippets'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_map = '<Plug>'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-rails'
on_map = '<Plug>'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = ['ruby']

[[plugins]]
repo = 'vim-scripts/ruby-matchit'
on_ft = ['ruby']

[[plugins]]
repo = 'Shougo/deoplete-rct'
on_ft = ['ruby']
in_i = 1
depends = ['vimproc.vim']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_source = '''
  let g:go_highlight_functions = 1
  let g:go_highlight_methods = 1
  let g:go_highlight_fields = 1
  let g:go_highlight_types = 1
  let g:go_highlight_operators = 1
  let g:go_highlight_build_constraints = 1
  let g:go_gocode_unimported_packages = 1
'''

[[plugins]]
repo = 'zchee/deoplete-go'
build = 'make'
on_ft = 'go'
in_i = 1
depends = ['deoplete.nvim']
hook_source = '''
  let g:deoplete#sources#go#gocode_binary = $GOPATH . '/bin/gocode'
'''

[[plugins]]
repo = 'zchee/deoplete-clang'
on_ft = ['c', 'cpp']
in_i = 1
depends = ['deoplete.nvim']
hook_source = '''
  let g:deoplete#sources#clang#libclang_path='/Library/Developer/CommandLineTools/usr/lib/libclang.dylib'
  let g:deoplete#sources#clang#clang_header='/Library/Developer/CommandLineTools/usr/lib/clang'
'''

[[plugins]]
repo = 'StanAngeloff/php.vim'
on_ft = ['php']
hook_source = '''
  let g:PHP_vintage_case_default_indent = 1
'''

[[plugins]]
repo = 'shawncplus/phpcomplete.vim'
on_ft = ['php']

[[plugins]]
repo = 'vim-perl/vim-perl'
on_ft = ['pl']

[[plugins]]
repo = 'udalov/kotlin-vim'
on_ft = ['kotlin']

[[plugins]]
repo = 'zchee/deoplete-zsh'
depends = ['deoplete.nvim']
on_ft = ['zsh']
in_i = 1

[[plugins]]
repo = 'zchee/deoplete-docker'
depends = ['deoplete.nvim']
on_ft = ['dockerfile']
in_i = 1

[[plugins]]
repo = 'hashivim/vim-vagrant'
on_ft = ['Vagrantfile']

[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = ['terraform']
hook_source = '''
  let g:terraform_fmt_on_save = 1
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']

[[plugins]]
repo = 'stephpy/vim-yaml'
on_ft = ['yaml']

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']

[[plugins]]
repo = 'JamshedVesuna/vim-markdown-preview'
on_ft = ['markdown']
hook_source = '''
  let g:vim_markdown_preview_github = 1
  let g:vim_markdown_preview_hotkey = '<C-m>'
  let g:vim_markdown_preview_browser = 'Google Chrome'
'''

[[plugins]]
repo = 'fszymanski/deoplete-emoji'
depends = ['deoplete.nvim']
on_ft = ['markdown']
in_i = 1

[[plugins]]
repo = 'aklt/plantuml-syntax'
on_ft = ['pu', 'uml', 'plantuml']
hook_source = '''
  let g:plantuml_executable_script = '~/.functions/plantuml'
'''

[[plugins]]
repo = 'spacewander/openresty-vim'
on_ft = ['nginx']

[[plugins]]
repo = 'tpope/vim-git'
on_ft = ['git', 'gitconfig', 'gitrebase', 'gitsendemail']

[[plugins]]
repo = 'itkq/fluentd-vim'
on_ft = ['fluentd']
