[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
  let NERDTreeShowHidden = 1
'''

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
hook_add = '''
  let g:nerdtree_tabs_open_on_console_startup = 1
'''

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
  let g:ale_sign_column_always = 1
  let g:ale_open_list = 1
  let g:ale_lint_on_text_changed = 'never'
  let g:ale_lint_on_enter = 0

  let g:ale_statusline_format = ['⨉ %d', '⚠ %d', '⬥ ok']
  let g:ale_sign_error = '⤫'
  let g:ale_sign_warning = '⚠'

  let g:ale_linters = {
    \ 'c': ['clang'],
    \ 'c++': ['clang'],
    \ 'php': ['php -l'],
    \ 'ruby': ['rubocop', 'ruby']
  \ }
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = {
    \ 'colorscheme': 'Dracula',
    \ 'active': {
    \   'left': [ ['mode', 'paste'],
    \             ['fugitive', 'filename', 'gitgutter', 'ale']
    \           ],
    \   'right': [ ['lineinfo'], ['percent'],
    \              ['ale_error', 'ale_warning', 'ale_ok', 'charcode', 'fileformat', 'fileencoding', 'filetype']
    \            ]
    \ },
    \ 'component': {
    \   'lineinfo': ' %3l:%-2v'
    \ },
    \ 'component_function_visible_condition': {
    \   'mode': 1,
    \ },
    \ 'component_expand': {
    \   'ale_error': 'LightLineAleError',
    \   'ale_warning': 'LightLineAleWarning',
    \   'ale_ok': 'LightLineAleOk',
    \ },
    \ 'component_type': {
    \   'ale_error': 'error',
    \   'ale_waring': 'waring',
    \   'ale_ok': 'ok',
    \ },
    \ 'component_function': {
    \   'fugitive': 'LightlineFugitive',
    \   'gitgutter': 'LightlineGitGutter',
    \   'filename': 'LightlineFilename',
    \   'ale': 'ALEGetStatusLine'
    \ },
    \ 'separator': { 'left': "\ue0b0", 'right': "\ue0b2" },
    \ 'subseparator': { 'left': "\ue0b1", 'right': "\ue0b3" },
  \ }
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'ap/vim-buftabline'
hook_add = '''
  let g:buftabline_numbers = 0
  let g:buftabline_indicators = 1
  let g:buftabline_separators = 1
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
build = ':UpdateRemotePlugins'
on_i = 1
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#enable_smart_case = 1
  let g:deoplete#auto_complete_start_length = 1
'''

[[plugins]]
repo = 'kassio/neoterm'
hook_source = '''
  let g:neoterm_position = 'horizontal'
  let g:neoterm_automap_keys = ',tt'
'''
