[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-textobj-function'

[[plugins]]
repo = 'osyo-manga/vim-operator-search'
depends = ['vim-operator-user', 'vim-textobj-function', 'vim-textobj-user']

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'AndrewRadev/splitjoin.vim'
hook_source = '''
  let g:splitjoin_split_mapping = ''
  let g:splitjoin_join_mapping = ''
'''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'
hook_source = '''
  let g:EditorConfig_exclude_patterns = ['scp://.*']
'''

[[plugins]]
repo = 'jiangmiao/auto-pairs'
on_i = 1

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = ['vim']
on_i = 1

[[plugins]]
repo = 'Shougo/neco-syntax'
on_i = 1

[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css']

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'styled-components/vim-styled-components'
on_ft = ['javascript', 'javascript.jsx', 'typescript', 'typescript.tsx']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript', 'typescript.tsx']

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_map = '<Plug>'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-rails'
on_map = '<Plug>'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = ['ruby']

[[plugins]]
repo = 'StanAngeloff/php.vim'
on_ft = ['php']
hook_source = '''
  let g:PHP_vintage_case_default_indent = 1
'''

[[plugins]]
repo = 'shawncplus/phpcomplete.vim'
on_ft = ['php']

[[plugins]]
repo = 'vim-perl/vim-perl'
on_ft = ['pl']

[[plugins]]
repo = 'zchee/deoplete-zsh'
depends = ['deoplete.nvim']
on_ft = ['zsh']
in_i = 1

[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = ['terraform']
hook_source = '''
  let g:terraform_fmt_on_save = 1
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']

[[plugins]]
repo = 'stephpy/vim-yaml'
on_ft = ['yaml']

[[plugins]]
repo = 'uarun/vim-protobuf'
on_ft = ['proto']

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']

[[plugins]]
repo = 'JamshedVesuna/vim-markdown-preview'
on_ft = ['markdown']
hook_source = '''
  let g:vim_markdown_preview_github = 1
  let g:vim_markdown_preview_hotkey = '<C-m>'
  let g:vim_markdown_preview_browser = 'Google Chrome'
'''

[[plugins]]
repo = 'spacewander/openresty-vim'
on_ft = ['nginx']

[[plugins]]
repo = 'tpope/vim-git'
on_ft = ['git', 'gitconfig', 'gitrebase', 'gitsendemail']

[[plugins]]
repo = 'itkq/fluentd-vim'
on_ft = ['fluentd']

[[plugins]]
repo = 'ekalinin/Dockerfile.vim'
on_ft = ['Dockerfile']

[[plugins]]
repo = 'jparise/vim-graphql'
on_ft = ['graphql']
