[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_add = '''
  let g:webdevicons_enable = 1

  let g:webdevicons_enable_nerdtree = 1

  let g:WebDevIconsUnicodeDecorateFolderNodes = 1
  let g:DevIconsEnableFoldersOpenClose = 1
  let g:WebDevIconsUnicodeDecorateFolderNodesDefaultSymbol = ''
  let g:DevIconsDefaultFolderOpenSymbol = ''
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  autocmd StdinReadPre * let s:std_in=1
  autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
  autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

  let NERDTreeShowHidden = 1
  let g:NERDTreeDirArrowExpandable = '▸'
  let g:NERDTreeDirArrowCollapsible = '▾'
'''

[[plugins]]
repo = 'tiagofumo/vim-nerdtree-syntax-highlight'
hook_add = '''
  let g:NERDTreeLimitedSyntax = 1
  let g:NERDTreeSyntaxDisableDefaultExtensions = 1
  let g:NERDTreeDisableExactMatchHighlight = 1
  let g:NERDTreeDisablePatternMatchHighlight = 1
  let g:NERDTreeSyntaxEnabledExtensions = ['rb', 'go', 'js', 'jsx', 'css', 'scss', 'html', 'sh'. 'zsh', 'conf', 'vim', 'md', 'yml', 'toml']
'''

[[plugins]]
repo = 'w0rp/ale'
build = '''
  gem install rubocop && \
  go get -u gopkg.in/alecthomas/gometalinter.v2 && \
  ln -sfv ${GOPATH}/bin/gometalinter.v2 ${GOPATH}/bin/gometalinter && \
  gometalinter --install --update && \
  npm install -g eslint && \
  brew install tflint && \
  luarocks install luacheck
'''
hook_add = '''
  " General
  let g:ale_sign_column_always = 1
  let g:ale_open_list = 1
  let g:ale_lint_on_text_changed = 'never'
  let g:ale_lint_on_enter = 0
  let g:ale_statusline_format = ['⨉ %d', '⚠ %d', '⬥ ok']
  let g:ale_sign_error = '⤫'
  let g:ale_sign_warning = '⚠'
  let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'

  " Lint
  let g:ale_linters = {
    \ 'c': ['clang'],
    \ 'c++': ['clang'],
    \ 'go': ['gometalinter'],
    \ 'php': ['php'],
    \ 'perl': ['perl'],
    \ 'ruby': ['ruby', 'rubocop'],
    \ 'javascript': ['eslint'],
    \ 'Terraform': ['tflint']
  \ }
  let g:ale_ruby_rubocop_executable = 'bundle'
  let g:ale_go_gometalinter_options = '--fast --enable=staticcheck --enable=gosimple --enable=unused'
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = {
    \ 'colorscheme': 'Dracula',
    \ 'active': {
    \   'left': [ ['mode', 'paste'],
    \             ['fugitive', 'filename', 'gitgutter', 'ale']
    \           ],
    \   'right': [ ['lineinfo'], ['percent'],
    \              ['ale_error', 'ale_warning', 'ale_ok', 'charcode', 'fileformat', 'fileencoding', 'filetype']
    \            ]
    \ },
    \ 'component': {
    \   'lineinfo': ' %3l:%-2v'
    \ },
    \ 'component_function_visible_condition': {
    \   'mode': 1,
    \ },
    \ 'component_expand': {
    \   'ale_error': 'LightLineAleError',
    \   'ale_warning': 'LightLineAleWarning',
    \   'ale_ok': 'LightLineAleOk',
    \ },
    \ 'component_type': {
    \   'ale_error': 'error',
    \   'ale_waring': 'waring',
    \   'ale_ok': 'ok',
    \ },
    \ 'component_function': {
    \   'fugitive': 'LightlineFugitive',
    \   'gitgutter': 'LightlineGitGutter',
    \   'filename': 'LightlineFilename',
    \   'filetype': 'LightlineFiletype',
    \   'fileformat': 'LightlineFileformat',
    \   'ale': 'ALEGetStatusLine'
    \ },
    \ 'separator': { 'left': "\ue0b0", 'right': "\ue0b2" },
    \ 'subseparator': { 'left': "\ue0b1", 'right': "\ue0b3" },
  \ }
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'ap/vim-buftabline'
hook_add = '''
  let g:buftabline_numbers = 0
  let g:buftabline_indicators = 1
  let g:buftabline_separators = 1
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
build = ':UpdateRemotePlugins'
on_i = 1
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#enable_smart_case = 1
  let g:deoplete#auto_complete_start_length = 2
'''

[[plugins]]
repo = 'kassio/neoterm'
hook_source = '''
  let g:neoterm_position = 'horizontal'
  let g:neoterm_automap_keys = ',tt'
'''

[[plugins]]
repo = 'junegunn/fzf.vim'
