[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'


[[plugins]]
repo = 'Shougo/context_filetype.vim'
hook_add = '''
  let g:context_filetype#filetypes = {
  \   'html': [
  \     {
  \       'start': '<script\%( [^>]*\)\?>',
  \       'end': '</script>', 'filetype': 'javascript',
  \     },
  \     {
  \       'start': '<style type="text/scss"\%( [^>]*\)\?>',
  \       'end': '</style>', 'filetype': 'scss',
  \     },
  \     {
  \       'start': '<style\%( [^>]*\)\?>',
  \       'end': '</style>', 'filetype': 'css',
  \     },
  \   ]
  \ }
'''

[[plugins]]
repo = 'osyo-manga/vim-precious'
