[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'
on_i = 1

[[plugins]]
repo = 'Shougo/neco-syntax'
on_i = 1

[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css']

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['js']

[[plugins]]
repo = 'othree/es.next.syntax.vim'
on_ft = ['js']

[[plugins]]
repo = 'marijnh/tern_for_vim'
on_ft = ['js']
build = 'npm install'

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = ['jsx']

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_map = '<Plug>'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-rails'
on_map = '<Plug>'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = ['ruby']

[[plugins]]
repo = 'vim-scripts/ruby-matchit'
on_ft = ['ruby']

[[plugins]]
repo = 'todesking/ruby_hl_lvar.vim'
on_ft = ['ruby']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_add = '''
  let g:go_highlight_functions = 1
  let g:go_highlight_methods = 1
  let g:go_highlight_fields = 1
  let g:go_highlight_types = 1
  let g:go_highlight_operators = 1
  let g:go_highlight_build_constraints = 1
'''

[[plugins]]
repo = 'StanAngeloff/php.vim'
on_ft = ['php']
hook_add = '''
  let g:PHP_vintage_case_default_indent = 1
'''

[[plugins]]
repo = 'shawncplus/phpcomplete.vim'
on_ft = ['php']

[[plugins]]
repo = 'vim-jp/cpp-vim'
on_ft = ['cpp']

[[plugins]]
repo = 'vim-perl/vim-perl'
on_ft = ['pl']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown', 'md']

[[plugins]]
repo = 'JamshedVesuna/vim-markdown-preview'
on_ft = ['markdown', 'md']
hook_add = '''
  let g:vim_markdown_preview_github = 1
  let g:vim_markdown_preview_hotkey = '<C-m>'
  let g:vim_markdown_preview_browser = 'Google Chrome'
'''

[[plugins]]
repo = 'JamshedVesuna/vim-markdown-preview'
on_ft = ['markdown', 'md']

[[plugins]]
repo = 'aklt/plantuml-syntax'
on_ft = ['pu', 'uml', 'plantuml']
hook_add = '''
  let g:plantuml_executable_script = '~/.functions/plantuml'
'''
